server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://114.55.245.123;databaseName=Kailong_Safe
    username: KaiLong_Safe
    password: powerSIS#123
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  global-config:
    db-config:
      # 全局默认主键类型
      id-type: auto
      table-underline: true
      logic-not-delete-value: 0
      logic-delete-value: 1
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.baomidou.mybatisplus: debug
exa:
  host: 114.55.245.123:9000
  get-value: ${exa.host}/data/SelectValueFloat
  get-values: ${exa.host}/data/SelectValuesFloat
  get-history: ${exa.host}/data/SelectDownsamplingRecordsFloat
  get-points: ${exa.host}/meta/SelectVariables
model:
  model-path: C:\work\model\yolov5s.onnx
  out-dir: C:\work\detection\
static:
  #  root: C:\work\民爆\图片\
  root: D:\deploy\images\
